apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: syft
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: syft
    app.kubernetes.io/part-of: syft
  name: syft
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: syft
status:
  loadBalancer: {}
